---
abstract: 'PL_check hacks using Perl callbacks'
author:
  - 'Chia-liang Kao <clkao@clkao.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  B::Utils: 0
  ExtUtils::Depends: 0
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: B-OPCheck
no_index:
  directory:
    - inc
    - t
requires:
  B::Utils: 0
  Scope::Guard: 0
  XSLoader: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.28
